api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
        multipart: ['multipart/form-data']
    patch_formats:
        json: ['application/merge-patch+json']
        jsonapi: ['application/vnd.api+json']
    swagger:
        versions: [3]
    error_formats:
        jsonproblem: [ 'application/problem+json' ]
        jsonld: [ 'application/ld+json' ]      # Hydra error formats
        jsonapi: [ 'application/vnd.api+json' ]
